import re
from SummaryNormalizationAction import SummaryNormalizationAction

##TODO
class SummaryNormalizer:
    def __init__(self):
        self.actions: list[SummaryNormalizationAction] = [
            SummaryNormalizationAction(
                name="remove or replace phrases",
                operation_type="remove or replace",
                explicit_mapping={
                    "risk to organizations": "",
                    "This trend": "",
                    "growing trend": "",
                    "The trend": "",
                    "the need for organizations": "",
                    "highlights the necessity": "",
                    "The vulnerability": "",
                    "thse activities": "",
                    "these areas": "",
                    "these vulnerabilities": "",
                    "emphasizes the": "",
                    "emphasizing the importance of": "",
                    "this highlights": "",
                    "critical security"
                    "need for" : "",
                    "this underscores": "",
                    "the importance of": "",
                    "to mitigate": "",
                    "to organizations": "",
                    "wide range": "",
                    "the need for": "",
                    "this calls for": "",
                    "this cluster of events": "",
                    "popular platforms": "",
                    "a Significant Risk": "",
                    "a significant threat": "",
                    "a significant risk": "",
                    "a significant security risk": "",
                    "a significant compromise": "",
                    "security teams": "",
                    "it operatives": "",
                    "advised to": "",
                    "it administrators": "",
                    "it professionals": "",
                    "has been": "",
                    "concerning trend": "",
                    "concerning trends": "",
                    "it teams": "",
                    "individual users": "",
                    "it departments": "",
                    "for businesses": "",
                    "for smbs": "",
                    "it is crucial": "",
                    "for heightened": "",
                    "measures and": "",
                    "represents a ": "",
                    "this poses": "",
                    "it poses": "",
                    "through several": "",
                    "This exploitation": "",
                    "An increasing trend": "",
                    "trends highlight": "",
                    "prevent exploitation": "",
                    "their installations": "",
                    "affected organizations": "",
                    "affected technologies": "",
                    "affected systems": "",
                    "immediate patching": "",
                    "the situation": "",
                    "reliant on": "",
                    "reassess their": "",
                    "organizations using": "",
                    "this highlights": "",
                    "conduct regular": "",
                    "security measures": "",
                    "that can lead": "",
                    "that could lead": "",
                    "that can be": "",
                    "it can be": "",
                    "heightened vigilance": "",
                    "industry implications": "",
                    "medium-sized": "",
                    "posed by": "",
                    "risks associated with": "",
                    "impacted by": "",
                    "who rely": "",
                    "that rely": "",
                    "it also": "",
                    "used by": "",
                    "urgent need": "",
                    "industry-wide": "",
                    "not only": "",
                    "but also": "",
                    "their clients": "",
                    "exploiting web vulnerabilities": "",
                    "have been": "",
                    "incidents highlight": "",
                    "broader industry": "",
                    "wake-up call": "",
                    "industry impact": "",
                    "has emerged": "",
                    "additionally": "",
                    "growing concern": "",
                    "issues highlight": "",
                    "has disclosed": "",
                    "development lifecycle": "",
                    "remain vigilant": "",
                    "web administrators": "",
                    "shedding light": "",
                    "attention from": "",
                    "illustrated by": "",
                    "critical need": "need",
                    "popular platforms": "platforms",
                    "troubling trend": "trend",
                    "collaborative efforts": "efforts",
                    "pressing need": ""
                }
            ),
            SummaryNormalizationAction(
                name="remove words",
                operation_type="remove",
                explicit_mapping={
                    "cybersecurity": "",
                    "emphasize": "",
                    "ensure": "",
                    "ensuring": "",
                    "carefully": "",
                    "operational": "",
                    "security": "",
                    "cybercriminals": "",
                    "heightened": "",
                    "businesses": "",
                    "efficiency": "",
                    "individuals": "",
                    "broader": "",
                    "underline": "",
                    "includes": "",
                    "imperative": "",
                    "similarly": "",
                    "numbers": "",
                    "indicating": "",
                    "necessitating": "",
                    "continuously": "",
                    "situation": "",
                    "potentially": "",
                    "necessitates": "",
                    "potential": "",
                    "handling": "",
                    "enhanced": "",
                    "comprehensive": "",
                    "reevaluation": "",
                    "crucial": "",
                    "developers": "",
                    "poses": "",
                    "indicates": "",
                    "importance": "",
                    "urgently": "",
                    "organizations": "",
                    "utilizing": "",
                    "consequences": "",
                    "affecting": "",
                    "prevent": "",
                    "protection": "",
                    "posing": "",
                    "protect": "",
                    "conduct": "",
                    "highlights": "",
                    "technology": "",
                    "recent": "",
                    "highlighting": "",
                    "implications": "",
                    "disclosures": "",
                    "underscore": "",
                    "underscores": "",
                    "necessity": "",
                    "necessitates": "",
                    "necessitate": "",
                    "immmediate": "",
                    "including": "",
                    "targeting": "",
                    "adopt": "",
                    "smbs": "",
                    "stringent": "",
                    "prioritize": "",
                    "robust": "",
                    "emphasizing": "",
                    "landscape": "",
                    "implement": "",
                    "particularly": "",
                    "recent": "",
                    "significant": "",
                    "further": "",
                    "companies": "",
                    "immediately": "",
                    "sophisticated": "",
                    "strong": "",
                    "experts": "",
                    "stressing": "",
                    "promptly": "",
                    "proactive": "",
                    "concerning": "",
                    "concern": "",
                    "rigorous": "",
                    "extent": "",
                    "thereby": "",
                    "such": "",
                    "using": "",
                    "urging": "",
                    "the": "",
                    "despite": "",
                    "surge": "",
                    "which": "",
                    "notably": "",
                    "this": "",
                    "a": "",
                    "securing": "",
                    "about": "",
                    "an": "",
                    "this": "",
                    "these": "",
                    "and": "",
                    "to": "",
                    "due": "",
                    "their": "",
                    "at": "",
                    "for": "",
                    "of": "",
                    "in": "",
                    "on": "",
                    "with": "",
                    "like": "",
                    "as": "",
                    "is": "",
                    "are": "",
                    "could": "",
                    "that": "",
                    "was": "",
                    "majorly": "",
                    "furthermore": "",
                    "were": "",
                    "against": "",
                    "must": "",
                    "should": "",
                    "indicate": "",
                    "aims": "",
                    ",": "",
                }
            )
        ]

    def normalize_string(self, summary: str) -> str:
        original = summary
        current = summary.strip().lower()

        for action in self.actions:
            current, applied = action.apply(current)
            print(f"[normalize_string] Applied '{applied}'\n → '{original}'\n → '{current}\n\n\n'")

        return current

    def normalize(self, summary: str) -> dict:
        normed = self.normalize_string(summary)
        return normed
