import os
from dotenv import load_dotenv

load_dotenv()

PUBLIC_API_URL=os.getenv("PUBLIC_API_URL")
GENERAL_REPORT_ENDPOINT=os.getenv("GENERAL_REPORT_ENDPOINT")
VULNERABILITIES_ENDPOINT=os.getenv("VULNERABILITIES_ENDPOINT")

SAST_SCAN_RESULT_BASE_URL=os.getenv("SAST_SCAN_RESULT_BASE_URL")
SAST_SCAN_RESULT_API_URL=os.getenv("SAST_SCAN_RESULT_API_URL")
