export default  [
    "Curated by Dieter Van der Stock, out of Antwerp, Belgium.",
    "You received this email because you subscribed via the Security Newsletter",
    "<https://securitynewsletter.co/?sid=6Oxov5s> site.",
    "We'll be sorry to see you go but you can unsubscribe instantly",
    "<https://securitynewsletter.co/unsubscribes/6Oxov5s>.",
    "1password.com <https://cur.at/eNbcDwC?m=email&sid=6Oxov5s>",
    "1Password: the password manager with (to me) the best UX",
    "<https://cur.at/eNbcDwC?m=email&sid=6Oxov5s>",
    "Supported by 1Password",
    "[image: Published with Curated]",
    "©2024 Security Newsletter | Privacy Policy",
    "<https://securitynewsletter.co/privacy?sid=6Oxov5s> | Contact:",
    "dieter@securitynewsletter.co",
    "From: Dieter Van der Stock <dieter@securitynewsletter.co>",
    "| Contact:",
];
